export const walletCryptoData = [
  {
    id: 1,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 2,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 3,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 4,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 5,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 6,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 7,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 8,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 9,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 10,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 11,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 12,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
  {
    id: 13,
    image:
      "https://demo.dashboardpack.com/cryptocurrency-html/img/currency/1.svg",
    text: "Bitcoin",
    senderId: "gdh-34um3bbj",
    transactionId: "HJD9R034JNN3N43",
    time: "10:23:45",
    status: "Completed",
    amount: "+0,041BTC",
  },
];
