export const invoiceData = [
  {
    id: 1,
    item: "Sport Shoe",
    desc: "export shoe",
    unit: "$99.00",
    qty: 1,
    total: "$99.00",
  },
  {
    id: 2,
    item: "Sport Shoe",
    desc: "export shoe",
    unit: "$99.00",
    qty: 1,
    total: "$99.00",
  },
  {
    id: 3,
    item: "Sport Shoe",
    desc: "export shoe",
    unit: "$99.00",
    qty: 1,
    total: "$99.00",
  },
  {
    id: 4,
    item: "Sport Shoe",
    desc: "export shoe",
    unit: "$99.00",
    qty: 1,
    total: "$99.00",
  },
  {
    id: 5,
    item: "Sport Shoe",
    desc: "export shoe",
    unit: "$99.00",
    qty: 1,
    total: "$99.00",
  },
  {
    id: 6,
    item: "Sport Shoe",
    desc: "export shoe",
    unit: "$99.00",
    qty: 1,
    total: "$99.00",
  },
  {
    id: 7,
    item: "Sport Shoe",
    desc: "export shoe",
    unit: "$99.00",
    qty: 1,
    total: "$99.00",
  },
];
